name: Static Code Analysis

on:
  - push

jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-18.04
    steps:
    
      # Check out the repository
      - uses: actions/checkout@v1

      # Install Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      # Install dependencies
      - run: npm ci --prefix src/
      - run: npm install --prefix src/map-app/

      # Run ESLint
      - run: npm run lint --prefix src/
      - run: npm run lint --prefix src/map-app/
